version: '3'
services:
  api:
    build:
      context: .
      args:
        MIX_ENV: dev
    environment:
      MIX_ENV: dev
      DB_SERVER: db
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - "./:/bnb"
    command: mix phx.server

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data
    ports:
      - '5432:5432'
    volumes:
      - "./data/data:/data"
